language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod --build-optimizer --vendor-chunk=true
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/eRSFw2eKbkYwIV-FD3HTO3zkV7ZyOqv7flJgEfK2TtVUuQiOJCOV8njWnV9MT86-"